"""Browser checks for multiline creation, appearance, and deliberate reconnection."""
from playwright.sync_api import sync_playwright, expect
import re
from browser_helpers import open_document_menu, edit_label, reveal, show_source, set_source, set_auto_apply, open_label_dialog, open_more, close_popovers, open_menu_details

with sync_playwright() as pw:
    browser = pw.chromium.launch(channel="chrome")
    page = browser.new_page(viewport={"width": 1440, "height": 1000})
    errors = []
    page.on("pageerror", lambda error: errors.append(str(error)))
    page.goto("http://127.0.0.1:8790/")
    open_document_menu(page)
    page.wait_for_function("document.querySelectorAll('#objects button').length >= 5")
    set_auto_apply(page, True)
    show_source(page)
    source = page.locator('#source')
    set_source(page, 'A: box "Input" at (0,0)\nB: box "Output" at (3,0)\nLink: arrow from A.e to B.w\n')
    page.wait_for_function("document.querySelectorAll('#objects button').length === 3")
    page.locator('#diagram [data-pikchr-id="o1"] text').click()
    page.locator('#appearance-selected').click()
    dialog=open_label_dialog(page)
    dialog.get_by_label('Canvas label',exact=True).fill('Input\nmanifest')
    dialog.get_by_label('Text sizing',exact=True).select_option('grow')
    expect(dialog.get_by_role('button',name='Done',exact=True)).to_be_enabled()
    dialog.get_by_role('button',name='Done',exact=True).click()
    expect(page.locator('#inspector').get_by_label('Current label',exact=True)).to_have_text('Input manifest')
    expect(page.locator('#diagram [data-pikchr-id="o1"] text')).to_have_count(2)
    open_more(page)
    page.get_by_label('Label behavior',exact=True).select_option('fixed')
    page.get_by_label('Shape width', exact=True).fill('1.7')
    page.get_by_label('Shape height', exact=True).fill('0.9')
    page.get_by_role('button',name='Apply size',exact=True).click()
    expect(source).to_have_value(re.compile(r'width 1\.7'))
    page.wait_for_function("!document.querySelector('#diagram').classList.contains('stale')")
    page.locator('#appearance-selected').click()
    page.get_by_label('Fill color', exact=True).fill('white')
    page.get_by_role('button', name='Update style', exact=True).click()
    expect(source).to_have_value(re.compile(r'width 1\.7'))
    expect(page.get_by_label('Fit shape to text', exact=True)).to_have_count(0)
    open_more(page)
    expect(page.get_by_label('Label behavior',exact=True)).to_have_value('fixed')
    edit_label(page, 'Keep uniform\ncard dimensions', 'fixed')
    expect(source).to_have_value(re.compile(r'"Keep uniform" "card dimensions".*width 1\.7 height 0\.9'))
    open_more(page)
    expect(page.get_by_label('Label behavior',exact=True)).to_have_value('fixed')
    close_popovers(page)
    page.locator('#diagram [data-pikchr-id="o3"]').click()
    reveal(page, '#route-selected').click()
    expect(page.locator('.anchor-target:visible')).to_have_count(0)
    page.get_by_role('button', name='Endpoints', exact=True).click()
    page.get_by_role('button', name='Reconnect on canvas', exact=True).click()
    assert page.locator('.anchor-target:visible').count() > 0
    page.get_by_role('button', name='Cancel reconnect', exact=True).click()
    expect(page.locator('.anchor-target:visible')).to_have_count(0)
    before = source.input_value()
    page.locator('#diagram [data-pikchr-id="o2"] text').click()
    expect(source).to_have_value(before)
    open_menu_details(page, 'Add shape')
    page.locator('#creation-tools').get_by_label('Shape', exact=True).select_option('text')
    page.get_by_label('Label', exact=True).fill('Section\ncaption')
    page.get_by_label('Object ID (optional)', exact=True).fill('Caption')
    page.get_by_label('X (inches)', exact=True).fill('1.25')
    page.get_by_label('Y (inches)', exact=True).fill('1.15')
    page.get_by_role('button', name='Add shape', exact=True).click()
    expect(source).to_have_value(re.compile(r'Caption: text'))
    expect(page.locator('#creation-tools').get_by_label('Shape', exact=True)).to_have_value('text')
    expect(page.get_by_label('Label', exact=True)).to_have_value('Section\ncaption')
    expect(page.get_by_label('Object ID (optional)', exact=True)).to_have_value('')
    page.locator('#creation-tools').get_by_label('Shape', exact=True).select_option('box')
    page.get_by_label('Label', exact=True).fill('Consistent card')
    page.locator('#creation-tools form details summary').filter(has_text='Size and style').click()
    page.get_by_label('New shape width (inches)', exact=True).fill('1.7')
    page.get_by_label('New shape height (inches)', exact=True).fill('0.9')
    page.get_by_label('New shape fill', exact=True).fill('white')
    expect(page.get_by_label('Fit label', exact=True)).not_to_be_checked()
    page.get_by_role('button', name='Add shape', exact=True).click()
    expect(source).to_have_value(re.compile(r'Consistent card.*width 1\.7.*height 0\.9'))
    expect(page.get_by_label('New shape width (inches)', exact=True)).to_have_value('1.7')
    expect(page.get_by_label('New shape height (inches)', exact=True)).to_have_value('0.9')
    expect(page.get_by_label('New shape fill', exact=True)).to_have_value('white')
    expect(page.get_by_label('Fit label', exact=True)).not_to_be_checked()
    assert not errors, errors
    browser.close()
    print('PASS: multiline labels, dimensions/style, safe reconnect, named text creation, persistent creation settings')
